name: 'FeedbackBuilder'
description: 'Structured logger, parser, and string builder built on rubricca to provide human-written feedback at machine-readable speeds'
inputs:
  rubricfile:  
    description: 'Rubric File location'
    required: true
    default: 'rubric.json'
  testresultfile:  
    description: 'Test Result Log File location'
    required: true
    default: 'stripetestresult.json'
  outputfolder:  
    description: 'Output Feedback File Folder location'
    required: true
    default: ''
outputs:
  passtestitems:
    description: 'List of test that Passed'
  failedtestitems:
    description: 'List of test that did not Passed'
runs:
  using: 'node12'
  main: 'dist/index.js'